### ISSUE TITLE
ToolInformationType problem

### ISSUE THREAD

**Issue by abulhol** [MAECProject/python-maec#78]
I am trying to add information on the Tool used in the Analysis, like this:
<pre>
from cybox.bindings.cybox_common import ToolInformationType
....
analysis = Analysis()
analysis.type_ = 'triage'
analysis.method = 'combination'
tool = ToolInformationType();
tool.Type = 'Sandbox'
tool.Name = 'Bla'
analysis.add_tool(tool)
</pre>

But as output I only get this:
<pre>
<maecPackage:Tools>
                        <maecPackage:Tool>
                            <cyboxCommon:Name>&lt;cybox.bindings.cybox_common.ToolInformationType object at 0x00000000047B0748&gt;</cyboxCommon:Name>
                        </maecPackage:Tool>
                    </maecPackage:Tools>
</pre>
What I am doing wrong?

**Comment by ikiril01** [comment]
Hi @abulhol, I think the issue is that you're using the CybOX binding class instead of the API class (a confusing distinction, I know - more on this [here](http://maec.readthedocs.org/en/stable/api_vs_bindings/index.html)). You'll also need to wrap the 'Sandbox' value in a VocabString instance, since the Type field in the ToolInformationType uses the ControlledVocabularyStringType. I think the following should work for you:

```python
from cybox.common import ToolInformation, VocabString
tool = ToolInformation()
tool.type_ = [VocabString("Sandbox")]
tool.name = "Bla"
```

**Comment by abulhol** [comment]
Hi Ivan, thank you so much. 
I thought I had already understood the difference between API and binding, but obviously not. :-)
