### ISSUE TITLE
UnicodeDecodeError installing 4.1.0.13

### ISSUE THREAD

**Issue by alecisec** [MAECProject/python-maec#94]
UnicodeDecodeError when attempting to install 4.1.0.13 (4.1.0.12 and 4.1.0.14 install fine)
OS - ubuntu:18.04

$pip3 install maec==4.1.0.13
Collecting maec==4.1.0.13
  Using cached https://files.pythonhosted.org/packages/bb/3d/b9075416ce1dd17ad866253b7c7987e52b78bb8b8c1c6dc23f4b1a94e51f/maec-4.1.0.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1suy8udn/maec/setup.py", line 24, in <module>
        readme = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 141: ordinal not in range(128)

**Comment by alecisec** [comment]
Same error when issuing the following commands:

git clone https://github.com/MAECProject/python-maec.git
git checkout tags//v4.1.0.13
python3 setup.py install

**Comment by gtback** [comment]
Hi, @alecisec , this was fixed in #93, and was released in 4.1.0.14. There shouldn't be any downsides to upgrading 4.1.0.13 to 4.1.0.14, but if that's a problem, let us know.

We can't release a "revised" version of 4.1.0.13. But applying [this change](https://github.com/MAECProject/python-maec/commit/109d4517b0123a5f01e31c15818f35772d451705) to the v4.1.0.13 tag should fix it.

**Comment by alecisec** [comment]
worked perfectly, thank you

**Comment by gtback** [comment]
@ikiril01 this can be closed.

**Comment by ikiril01** [comment]
@gtback thanks! :)
